package com.z7dream.lib.db.bean;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;

/**
 * 文件星标
 * <p>
 * Created by Z7Dream on 2017/7/4 13:38.
 * Email:zhangxyfs@126.com
 */
@Entity
public class FileStarInfo {
    @Id
    private long id;

    private String userToken;//用户token

    private String filePath;

    @Generated(2056579482)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public FileStarInfo(long id, String userToken, String filePath) {
        this.id = id;
        this.userToken = userToken;
        this.filePath = filePath;
    }

    @Generated(298402998)
    public FileStarInfo() {
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getUserToken() {
        return userToken;
    }

    public void setUserToken(String userToken) {
        this.userToken = userToken;
    }

    public String getFilePath() {
        return filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

}
