package com.z7dream.lib.db.bean;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Index;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;

/**
 * 文件元数据
 * <p>
 * Created by Z7Dream on 2017/7/4 11:34.
 * Email:zhangxyfs@126.com
 */

@Entity
public class FileInfo {
    @Id
    private long id;

    private String fileName;//文件名

    @Index
    private String filePath;//文件路径

    @Index
    private String parentPath;//父文件夹路径

    private String extension;//扩展名

    private long createTime;//创建时间

    @Index
    private long lastModifyTime;//最后修改时间

    private long fileSize;//文件大小

    private boolean isFile;//是否文件

    @Index
    private String fileType;//文件类型

    @Generated(1546775479)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public FileInfo(long id, String fileName, String filePath, String parentPath,
            String extension, long createTime, long lastModifyTime, long fileSize,
            boolean isFile, String fileType) {
        this.id = id;
        this.fileName = fileName;
        this.filePath = filePath;
        this.parentPath = parentPath;
        this.extension = extension;
        this.createTime = createTime;
        this.lastModifyTime = lastModifyTime;
        this.fileSize = fileSize;
        this.isFile = isFile;
        this.fileType = fileType;
    }

    @Generated(1367591352)
    public FileInfo() {
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getFilePath() {
        return filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    public String getParentPath() {
        return parentPath;
    }

    public void setParentPath(String parentPath) {
        this.parentPath = parentPath;
    }

    public String getExtension() {
        return extension;
    }

    public void setExtension(String extension) {
        this.extension = extension;
    }

    public long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(long createTime) {
        this.createTime = createTime;
    }

    public long getLastModifyTime() {
        return lastModifyTime;
    }

    public void setLastModifyTime(long lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    public long getFileSize() {
        return fileSize;
    }

    public void setFileSize(long fileSize) {
        this.fileSize = fileSize;
    }

    public boolean getIsFile() {
        return isFile;
    }

    public void setIsFile(boolean isFile) {
        this.isFile = isFile;
    }

    public String getFileType() {
        return fileType;
    }

    public void setFileType(String fileType) {
        this.fileType = fileType;
    }
}
