package com.z7dream.lib.db.bean;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;

/**
 * 文件星标
 * <p>
 * Created by Z7Dream on 2017/7/4 13:38.
 * Email:zhangxyfs@126.com
 */
@Entity
public class FileStarInfo {
    @Id
    private long id;

    private long userId;//用户id

    private String filePath;

    @Generated(630423849)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public FileStarInfo(long id, long userId, String filePath) {
        this.id = id;
        this.userId = userId;
        this.filePath = filePath;
    }

    @Generated(298402998)
    public FileStarInfo() {
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public String getFilePath() {
        return filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

}
