package com.z7dream.lib.db.bean;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;

/**
 * 文件类型：数据固定
 * <p>
 * Created by Z7Dream on 2017/7/4 11:44.
 * Email:zhangxyfs@126.com
 */
@Entity
public class FileTypeInfo {
    @Id(assignable = true)
    private long id;

    private String typeName;//文件类型名称

    private String format;//格式(扩展名)

    public FileTypeInfo(String typeName, String format) {
        this.typeName = typeName;
        this.format = format;
    }

    @Generated(642009613)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public FileTypeInfo(long id, String typeName, String format) {
        this.id = id;
        this.typeName = typeName;
        this.format = format;
    }

    @Generated(1312591050)
    public FileTypeInfo() {
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getTypeName() {
        return typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    public String getFormat() {
        return format;
    }

    public void setFormat(String format) {
        this.format = format;
    }
}
